import type { ToolDefinition } from "./types";

const operationalOptions = [
  { label: "No reliable process", value: "0" },
  { label: "Manual and inconsistent", value: "0.35" },
  { label: "Documented, but not always followed", value: "0.7" },
  { label: "Consistent, measured, and owned", value: "1" },
];

export const assessmentTools: ToolDefinition[] = [
  {
    slug: "revenue-leak-scorecard",
    eyebrow: "Revenue-system scorecard",
    title: "Where Is Your Booked Revenue Leaking?",
    description:
      "Score the systems between a new inquiry and a booked job, then see the three gaps most likely to deserve attention.",
    timeEstimate: "About 3 minutes",
    questions: [
      {
        id: "monthlyLeads",
        label: "How many inbound calls and leads do you receive in a typical month?",
        help: "Use your best estimate across phone, forms, chat, and direct messages.",
        type: "number",
        min: 0,
        max: 100000,
        step: 1,
        suffix: "leads",
        placeholder: "150",
      },
      {
        id: "missedCallHandling",
        label: "What happens when your team misses a call?",
        type: "select",
        options: [
          { label: "Nothing consistent", value: "0" },
          { label: "Someone checks voicemail later", value: "0.3" },
          { label: "Same-day manual callback or text", value: "0.65" },
          { label: "Immediate automated text and assigned follow-up", value: "1" },
        ],
      },
      {
        id: "averageJobValue",
        label: "What is the average value of a booked job?",
        type: "number",
        min: 0,
        max: 10000000,
        step: 100,
        prefix: "$",
        placeholder: "4,500",
      },
      {
        id: "responseTime",
        label: "How quickly does a new sales opportunity usually receive a human response?",
        type: "select",
        options: [
          { label: "More than one business day", value: "0" },
          { label: "Within the same business day", value: "0.4" },
          { label: "Within one hour", value: "0.75" },
          { label: "Within 15 minutes", value: "1" },
        ],
      },
      {
        id: "openEstimateCount",
        label: "How many estimates are currently open?",
        type: "number",
        min: 0,
        max: 100000,
        step: 1,
        suffix: "estimates",
        placeholder: "28",
      },
      {
        id: "openEstimateValue",
        label: "What is the approximate total value of those open estimates?",
        type: "number",
        min: 0,
        max: 1000000000,
        step: 100,
        prefix: "$",
        placeholder: "185,000",
      },
      {
        id: "followUpCadence",
        label: "How many proactive follow-ups does each estimate normally receive?",
        type: "select",
        options: [
          { label: "None", value: "0" },
          { label: "One", value: "0.35" },
          { label: "Two or three", value: "0.75" },
          { label: "Four or more with stop rules", value: "1" },
        ],
      },
      {
        id: "crmCompleteness",
        label: "How reliably is opportunity status maintained in your CRM or field-service software?",
        type: "select",
        options: [
          { label: "We do not use one", value: "0" },
          { label: "We use spreadsheets or scattered tools", value: "0.25" },
          { label: "We have a system, but records are often incomplete", value: "0.6" },
          { label: "Statuses and next steps are consistently current", value: "1" },
        ],
      },
      {
        id: "afterHoursCoverage",
        label: "What happens to inquiries that arrive after hours?",
        type: "select",
        options: [
          { label: "Voicemail or an unmonitored inbox", value: "0" },
          { label: "Reviewed the next business day", value: "0.35" },
          { label: "Acknowledged immediately, then routed", value: "0.75" },
          { label: "Captured, qualified, and assigned 24/7", value: "1" },
        ],
      },
      {
        id: "opportunityOwnership",
        label: "Does every active opportunity have one accountable owner?",
        type: "select",
        options: [
          { label: "No", value: "0" },
          { label: "Usually, but it is informal", value: "0.5" },
          { label: "Yes, with a visible next action", value: "1" },
        ],
      },
      {
        id: "sourceTracking",
        label: "Can you connect booked jobs back to their original lead source?",
        type: "select",
        options: [
          { label: "Rarely or never", value: "0" },
          { label: "For some channels", value: "0.45" },
          { label: "For most opportunities", value: "0.75" },
          { label: "Yes, consistently", value: "1" },
        ],
      },
      {
        id: "ownerIndependence",
        label: "Could this lead-to-booked-job system operate for 10 business days without the owner?",
        type: "select",
        options: [
          { label: "No—the process would largely stop", value: "0" },
          { label: "Only with major gaps or constant calls", value: "0.35" },
          { label: "Mostly, with a few owner decisions", value: "0.7" },
          { label: "Yes—the team and systems can run it", value: "1" },
        ],
      },
    ],
  },
  {
    slug: "missed-call-calculator",
    eyebrow: "Revenue exposure calculator",
    title: "What Are Missed Calls Costing Your Business?",
    description:
      "Model a range of monthly and annual revenue that may be exposed when qualified calls go unanswered.",
    timeEstimate: "About 90 seconds",
    questions: [
      {
        id: "callsPerMonth",
        label: "How many inbound calls do you receive each month?",
        type: "number",
        min: 0,
        max: 100000,
        step: 1,
        suffix: "calls",
        placeholder: "300",
      },
      {
        id: "missedCallPercentage",
        label: "What percentage of those calls do you estimate are missed?",
        help: "If you are unsure, use a conservative estimate rather than an industry average.",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        suffix: "%",
        placeholder: "18",
      },
      {
        id: "salesOpportunityPercentage",
        label: "What percentage of inbound calls are genuine sales opportunities?",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        suffix: "%",
        placeholder: "65",
      },
      {
        id: "bookingRate",
        label: "What percentage of qualified calls normally become booked jobs?",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        suffix: "%",
        placeholder: "35",
      },
      {
        id: "averageJobValue",
        label: "What is the average booked-job value?",
        type: "number",
        min: 0,
        max: 10000000,
        step: 100,
        prefix: "$",
        placeholder: "3,500",
      },
      {
        id: "grossMarginRange",
        label: "What is your typical gross-margin range?",
        type: "select",
        options: [
          { label: "15%–25%", value: "15-25" },
          { label: "25%–35%", value: "25-35" },
          { label: "35%–45%", value: "35-45" },
          { label: "45%–60%", value: "45-60" },
          { label: "60%–75%", value: "60-75" },
        ],
      },
    ],
  },
  {
    slug: "estimate-follow-up-gap",
    eyebrow: "Estimate pipeline check",
    title: "How Much Revenue Is Sitting in Your Open Estimates?",
    description:
      "Measure follow-up maturity and model the value of applying a consistent next-action process to existing demand.",
    timeEstimate: "About 2 minutes",
    questions: [
      {
        id: "estimatesPerMonth",
        label: "How many estimates do you issue in a typical month?",
        type: "number",
        min: 0,
        max: 100000,
        step: 1,
        suffix: "estimates",
        placeholder: "45",
      },
      {
        id: "averageEstimateSize",
        label: "What is the average estimate value?",
        type: "number",
        min: 0,
        max: 10000000,
        step: 100,
        prefix: "$",
        placeholder: "8,000",
      },
      {
        id: "currentCloseRate",
        label: "What is your current estimate close rate?",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        suffix: "%",
        placeholder: "32",
      },
      {
        id: "open7To13",
        label: "How many open estimates are 7–13 days old?",
        type: "number",
        min: 0,
        max: 100000,
        step: 1,
        placeholder: "12",
      },
      {
        id: "open14To29",
        label: "How many open estimates are 14–29 days old?",
        type: "number",
        min: 0,
        max: 100000,
        step: 1,
        placeholder: "9",
      },
      {
        id: "open30Plus",
        label: "How many open estimates are 30 days old or older?",
        type: "number",
        min: 0,
        max: 100000,
        step: 1,
        placeholder: "7",
      },
      {
        id: "followUpCount",
        label: "How many proactive follow-ups does each estimate normally receive?",
        type: "select",
        options: [
          { label: "None", value: "0" },
          { label: "One", value: "0.35" },
          { label: "Two", value: "0.65" },
          { label: "Three or more with stop rules", value: "1" },
        ],
      },
      {
        id: "ownerAndNextAction",
        label: "Does every open estimate have both an owner and a dated next action?",
        type: "boolean",
      },
    ],
  },
  {
    slug: "seller-independence-check",
    eyebrow: "Succession readiness check",
    title: "Could Your Business Run for 10 Business Days Without You?",
    description:
      "Assess how much the revenue process depends on the owner and how transferable that process appears today.",
    timeEstimate: "About 2 minutes",
    questions: [
      {
        id: "missedCallRecovery",
        label: "Missed calls are recovered without the owner stepping in.",
        type: "select",
        options: operationalOptions,
      },
      {
        id: "estimateFollowUp",
        label: "Estimate follow-up continues consistently without owner reminders.",
        type: "select",
        options: operationalOptions,
      },
      {
        id: "afterHoursRouting",
        label: "After-hours inquiries are captured and routed automatically.",
        type: "select",
        options: operationalOptions,
      },
      {
        id: "crmOwnership",
        label: "Every opportunity has a non-owner assignee and current next action.",
        type: "select",
        options: operationalOptions,
      },
      {
        id: "processDocumentation",
        label: "Lead intake, qualification, estimating, and follow-up are documented.",
        type: "select",
        options: operationalOptions,
      },
      {
        id: "credentialDocumentation",
        label: "Critical systems, access, and credential ownership are documented securely.",
        type: "select",
        options: operationalOptions,
      },
      {
        id: "exceptionHandling",
        label: "The team can resolve common exceptions without asking the owner.",
        type: "select",
        options: operationalOptions,
      },
      {
        id: "managementReporting",
        label: "Management receives reliable revenue-pipeline reporting without owner assembly.",
        type: "select",
        options: operationalOptions,
      },
    ],
  },
];

export function getAssessmentTool(slug: string): ToolDefinition | undefined {
  return assessmentTools.find((tool) => tool.slug === slug);
}

